extends Node
## Central audio manager. Autoloaded as `AudioManager`.
##
## Responsibilities:
##  - looping ambient soundscape + heartbeat (low sanity feedback)
##  - named SFX playback: play_2d (UI/player-local) and play_3d (spatial)
##  - footstep helper that also feeds the AI hearing system
##  - `noise_emitted` signal: every gameplay sound that an enemy could
##    hear is emitted with a world position and loudness factor.
##
## All WAVs are procedurally generated by tools/generate_audio.py so the
## project is fully self-contained.

## Enemies subscribe to this. loudness is a multiplier around 1.0
## (crouch-walk ~0.3, walking ~0.7, sprinting ~1.4).
signal noise_emitted(world_position: Vector3, loudness: float)

const SOUNDS := {
	"footstep": [
		preload("res://assets/audio/footstep_1.wav"),
		preload("res://assets/audio/footstep_2.wav"),
		preload("res://assets/audio/footstep_3.wav"),
		preload("res://assets/audio/footstep_4.wav"),
	],
	"enemy_step": [preload("res://assets/audio/enemy_step.wav")],
	"door_creak": [preload("res://assets/audio/door_creak.wav")],
	"door_locked": [preload("res://assets/audio/door_locked.wav")],
	"pickup": [preload("res://assets/audio/pickup.wav")],
	"note": [preload("res://assets/audio/note_rustle.wav")],
	"jumpscare": [preload("res://assets/audio/jumpscare.wav")],
	"growl": [preload("res://assets/audio/enemy_growl.wav")],
	"flicker": [preload("res://assets/audio/flicker.wav")],
	"escape": [preload("res://assets/audio/escape_sting.wav")],
	"blip": [preload("res://assets/audio/blip.wav")],
}

var ambient: AudioStreamPlayer
var heartbeat: AudioStreamPlayer
var rng := RandomNumberGenerator.new()


func _ready() -> void:
	rng.randomize()
	process_mode = Node.PROCESS_MODE_ALWAYS

	ambient = AudioStreamPlayer.new()
	ambient.stream = preload("res://assets/audio/ambient_drone.wav")
	ambient.volume_db = -16.0
	ambient.bus = "Master"
	add_child(ambient)
	ambient.play()

	heartbeat = AudioStreamPlayer.new()
	heartbeat.stream = preload("res://assets/audio/heartbeat.wav")
	heartbeat.volume_db = -8.0
	add_child(heartbeat)


## Fire-and-forget non-positional sound (UI, player-local events).
func play_2d(sound_name: String, volume_db := 0.0) -> void:
	var arr: Array = SOUNDS.get(sound_name, [])
	if arr.is_empty():
		return
	var p := AudioStreamPlayer.new()
	p.stream = arr[rng.randi() % arr.size()]
	p.volume_db = volume_db
	p.finished.connect(p.queue_free)
	add_child(p)
	p.play()


## Fire-and-forget spatial sound at a world position.
## `parent` defaults to the current scene so the node is freed correctly
## on scene reload.
func play_3d(sound_name: String, pos: Vector3, volume_db := 0.0, parent: Node = null) -> AudioStreamPlayer3D:
	var arr: Array = SOUNDS.get(sound_name, [])
	if arr.is_empty():
		return null
	var p := AudioStreamPlayer3D.new()
	p.stream = arr[rng.randi() % arr.size()]
	p.unit_size = 4.0
	p.max_distance = 34.0
	p.volume_db = volume_db
	var host := parent if parent != null else get_tree().current_scene
	if host == null:
		host = self
	host.add_child(p)
	p.global_position = pos
	p.finished.connect(p.queue_free)
	p.play()
	return p


## A player footstep: audible spatial sound AND a noise event for AI hearing.
func footstep(pos: Vector3, loudness := 1.0) -> void:
	play_3d("footstep", pos, -8.0 + 4.0 * (loudness - 0.7))
	emit_noise(pos, loudness)


## Any gameplay sound that the enemy could plausibly hear goes through here.
func emit_noise(pos: Vector3, loudness := 1.0) -> void:
	noise_emitted.emit(pos, loudness)


## Low-sanity heartbeat loop.
func set_heartbeat(on: bool) -> void:
	if on and not heartbeat.playing:
		heartbeat.play()
	elif not on and heartbeat.playing:
		heartbeat.stop()


func stop_ambient() -> void:
	if ambient.playing:
		ambient.stop()
